package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Member;

public interface MemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MEMBER
     *
     * @mbg.generated Wed Apr 19 12:05:35 EEST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MEMBER
     *
     * @mbg.generated Wed Apr 19 12:05:35 EEST 2023
     */
    int insert(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MEMBER
     *
     * @mbg.generated Wed Apr 19 12:05:35 EEST 2023
     */
    Member selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MEMBER
     *
     * @mbg.generated Wed Apr 19 12:05:35 EEST 2023
     */
    List<Member> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MEMBER
     *
     * @mbg.generated Wed Apr 19 12:05:35 EEST 2023
     */
    int updateByPrimaryKey(Member record);
}