package lt.vu.mybatis.model;

public class Member {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MEMBER.ID
     *
     * @mbg.generated Wed Apr 19 12:05:35 EEST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MEMBER.PASSWORD
     *
     * @mbg.generated Wed Apr 19 12:05:35 EEST 2023
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MEMBER.USERNAME
     *
     * @mbg.generated Wed Apr 19 12:05:35 EEST 2023
     */
    private String username;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MEMBER.ID
     *
     * @return the value of PUBLIC.MEMBER.ID
     *
     * @mbg.generated Wed Apr 19 12:05:35 EEST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MEMBER.ID
     *
     * @param id the value for PUBLIC.MEMBER.ID
     *
     * @mbg.generated Wed Apr 19 12:05:35 EEST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MEMBER.PASSWORD
     *
     * @return the value of PUBLIC.MEMBER.PASSWORD
     *
     * @mbg.generated Wed Apr 19 12:05:35 EEST 2023
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MEMBER.PASSWORD
     *
     * @param password the value for PUBLIC.MEMBER.PASSWORD
     *
     * @mbg.generated Wed Apr 19 12:05:35 EEST 2023
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MEMBER.USERNAME
     *
     * @return the value of PUBLIC.MEMBER.USERNAME
     *
     * @mbg.generated Wed Apr 19 12:05:35 EEST 2023
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MEMBER.USERNAME
     *
     * @param username the value for PUBLIC.MEMBER.USERNAME
     *
     * @mbg.generated Wed Apr 19 12:05:35 EEST 2023
     */
    public void setUsername(String username) {
        this.username = username;
    }
}