package lt.vu.mybatis.model;

public class Tasklist {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TASKLIST.ID
     *
     * @mbg.generated Wed Apr 19 12:05:35 EEST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TASKLIST.NAME
     *
     * @mbg.generated Wed Apr 19 12:05:35 EEST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TASKLIST.MEMBER_ID
     *
     * @mbg.generated Wed Apr 19 12:05:35 EEST 2023
     */
    private Integer memberId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TASKLIST.ID
     *
     * @return the value of PUBLIC.TASKLIST.ID
     *
     * @mbg.generated Wed Apr 19 12:05:35 EEST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TASKLIST.ID
     *
     * @param id the value for PUBLIC.TASKLIST.ID
     *
     * @mbg.generated Wed Apr 19 12:05:35 EEST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TASKLIST.NAME
     *
     * @return the value of PUBLIC.TASKLIST.NAME
     *
     * @mbg.generated Wed Apr 19 12:05:35 EEST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TASKLIST.NAME
     *
     * @param name the value for PUBLIC.TASKLIST.NAME
     *
     * @mbg.generated Wed Apr 19 12:05:35 EEST 2023
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TASKLIST.MEMBER_ID
     *
     * @return the value of PUBLIC.TASKLIST.MEMBER_ID
     *
     * @mbg.generated Wed Apr 19 12:05:35 EEST 2023
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TASKLIST.MEMBER_ID
     *
     * @param memberId the value for PUBLIC.TASKLIST.MEMBER_ID
     *
     * @mbg.generated Wed Apr 19 12:05:35 EEST 2023
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }
}