package lt.vu.mybatis.model;

public class Task {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TASK.ID
     *
     * @mbg.generated Wed Apr 19 12:05:35 EEST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TASK.NAME
     *
     * @mbg.generated Wed Apr 19 12:05:35 EEST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TASK.PRIORITY
     *
     * @mbg.generated Wed Apr 19 12:05:35 EEST 2023
     */
    private Integer priority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TASK.STATUS
     *
     * @mbg.generated Wed Apr 19 12:05:35 EEST 2023
     */
    private Boolean status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TASK.LIST_ID
     *
     * @mbg.generated Wed Apr 19 12:05:35 EEST 2023
     */
    private Integer listId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TASK.ID
     *
     * @return the value of PUBLIC.TASK.ID
     *
     * @mbg.generated Wed Apr 19 12:05:35 EEST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TASK.ID
     *
     * @param id the value for PUBLIC.TASK.ID
     *
     * @mbg.generated Wed Apr 19 12:05:35 EEST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TASK.NAME
     *
     * @return the value of PUBLIC.TASK.NAME
     *
     * @mbg.generated Wed Apr 19 12:05:35 EEST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TASK.NAME
     *
     * @param name the value for PUBLIC.TASK.NAME
     *
     * @mbg.generated Wed Apr 19 12:05:35 EEST 2023
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TASK.PRIORITY
     *
     * @return the value of PUBLIC.TASK.PRIORITY
     *
     * @mbg.generated Wed Apr 19 12:05:35 EEST 2023
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TASK.PRIORITY
     *
     * @param priority the value for PUBLIC.TASK.PRIORITY
     *
     * @mbg.generated Wed Apr 19 12:05:35 EEST 2023
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TASK.STATUS
     *
     * @return the value of PUBLIC.TASK.STATUS
     *
     * @mbg.generated Wed Apr 19 12:05:35 EEST 2023
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TASK.STATUS
     *
     * @param status the value for PUBLIC.TASK.STATUS
     *
     * @mbg.generated Wed Apr 19 12:05:35 EEST 2023
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TASK.LIST_ID
     *
     * @return the value of PUBLIC.TASK.LIST_ID
     *
     * @mbg.generated Wed Apr 19 12:05:35 EEST 2023
     */
    public Integer getListId() {
        return listId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TASK.LIST_ID
     *
     * @param listId the value for PUBLIC.TASK.LIST_ID
     *
     * @mbg.generated Wed Apr 19 12:05:35 EEST 2023
     */
    public void setListId(Integer listId) {
        this.listId = listId;
    }
}